CREATE TABLE `2016_articles` (
  `id` int(8) unsigned NOT NULL,
  `date` date DEFAULT NULL,
  `titre` text,
  `page` enum('g','u') DEFAULT NULL,
  `contenu_resume` text,
  `contenu_long` text
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

INSERT INTO `2016_articles` (`id`, `date`, `titre`, `page`, `contenu_resume`, `contenu_long`) VALUES
(1, '2016-05-17', 'lkazbfoiuazhrofiuhazoiurghoi', 'g', 'vzlkejhgoiuzehgoizugo', 'aelrkughoieauhgoiazuehrgoizuehgio'),
(2, '2016-05-10', 'TOMSIZE sera présent à l''UTCéenne 2016 !', 'u', 'Il sera là !', '<p style="text-align: justify;">\r\n						Retrouvez TOMSIZE à l''UTCéenne 2015 !\r\n						Ce Dj parisien a d''abord produit de la Dubstep et du HipHop, avant d''émerger avec sa trap original à base de basses dévastatrices. Ses remix avec Simeon lui ont permi de se faire une place dans le milieu électro.\r\n						Découvrer Tomsize avec son morceau "Jump" :\r\n						</p>\r\n						<hr class = "margin_bottom margin_top">\r\n						<div class="embed-responsive embed-responsive-16by9">\r\n							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/YgWFqRDfNkU"></iframe>\r\n						</div>'),
(4, '2016-05-19', 'Partenariat Société Générale', 'u', 'La SoGé est toujours présente!', '						<p>\r\n						Salut à toi ! <br/>\r\n						Cette année encore, ta banque préférée la Société Générale ne te rembourse pas un seul, mais les deux évènements d''Etuville 2016 : l''UTCéenne et le Gala UTC sur ouverture de compte dans leur agence !\r\n						<br/>\r\n						Pour obtenir ce remboursement rien de plus simple : 						<br/>\r\n						- Va à la SOGE ouvrir ton compte avec : ta place / carte d''identité / justificatif de domicile <br>\r\n						- 36€ seront immédiatement crédités sur ton compte (quelque soit le type de place) <br>\r\n						- Achète ta place pour la Gala UTC 2016 (en vente après l''UTCéenne)<br>\r\n						- Retourne voir la SOGE avec ta place<br>\r\n						- 25€ seront crédités sur ton compte<br><br>\r\n						On rappelle que l''ouverture d''un compte à la Société générale n''entraine aucun frais pendant toute la durée de ta scolarité. <br>\r\n						Allez hop hop hop !\r\n						Ca prend sa place et ça ouvre son compte !\r\n						Etu-bisous </p>\r\n						<hr class="margin_bottom margin_top">\r\n						<div class="embed-responsive embed-responsive-16by9">\r\n							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/5j3pCwKzBys"></iframe>\r\n						</div>'),
(5, '2016-05-19', 'Partenariat avec la société générale', 'g', 'La société générale vous rembourse vos évènements !', '						<p>Salut à toi !<br/>\r\n						Cette année encore, ta banque préférée la Société Générale ne te rembourse pas un seul, mais les deux évènements d''Etuville 2015 : l''UTCéenne et le Gala UTC sur ouverture de compte dans leur agence !\r\n						<br/>\r\n						Pour obtenir ce remboursement rien de plus simple : 						<br/>\r\n						- Va à la SOGE ouvrir ton compte avec : ta place / carte d''identité / justificatif de domicile <br>\r\n						- 36€ seront immédiatement crédités sur ton compte (quelque soit le type de place) <br>\r\n						- Achète ta place pour la Gala UTC 2016 (en vente après l''UTCéenne)<br>\r\n						- Retourne voir la SOGE avec ta place<br>\r\n						- 25€ seront crédités sur ton compte<br><br>\r\n						On rappelle que l''ouverture d''un compte à la Société générale n''entraine aucun frais pendant toute la durée de ta scolarité. <br>\r\n						Allez hop hop hop !\r\n						Ca prend sa place et ça ouvre son compte !\r\n						Etu-bisous </p>\r\n						<hr class = "margin_bottom margin_top">\r\n						<div class="embed-responsive embed-responsive-16by9">\r\n							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/C2FQSKrWwCE"></iframe>\r\n						</div>'),
(6, '2016-05-23', 'Feder sera au Gala !', 'g', 'Venez voir Feder au Gala !', '						<p style="text-align: justify;">\r\n							De son vrai nom Hadrien Federiconi, Feder est originaire de Nice. Il compte parmi les grands noms de la deep-house française, grâce à son titre «Goodbye ft Lyse» qui connait en ce moment un gros succès dans toute l''Europe. Ecoutez son single "Goodbye" !\r\n						</p>\r\n					<hr class = "margin_bottom margin_top">\r\n					<div class="embed-responsive embed-responsive-16by9">\r\n					<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Mptdcx36qZU"></iframe>\r\n					</div>'),
(7, '2016-05-22', 'zergzrtgertgertherth', 'u', 'contenu court', 'jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn jkngoizehrgoiu pozjrgoiuzhrn ');

ALTER TABLE `2016_articles`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `2016_articles`
  MODIFY `id` int(8) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
  